### ISSUE TITLE
Unable to get Attendance Details display in salary slip.

### ISSUE THREAD

**Issue by AapicoDev** [navariltd/nl-attendance-timesheet#13]
Sorry I am newbie to Frappe, I have an issue that Attendance Details in Salary Slips Tab not show up the data. 

@frappe.whitelist()
def add_attendance_data(payroll_entry):
    salary_slips = frappe.db.get_all('Salary Slip', filters = { 'payroll_entry': payroll_entry, 'docstatus': 0 })

I wonder how this session of code being call, so that data could be added to salary_slips?

**Comment by maniamartial** [comment]
Fixed.

That method was being consumed in another app, have updated, check on payroll entry js.
Let me get your feedback incase of anything else.
WiIl close this in weeks time
