### ISSUE TITLE
Error while trying to open Navari Custom Payroll Settings DocType

### ISSUE THREAD

**Issue by ramanduck** [navariltd/nl-attendance-timesheet#9]
Getting an error while trying to open Navari Custom Payroll Settings DocType: 

DocType Earned Bonus vs Attained Score not found

<img width="1299" alt="Screenshot 2024-07-27 at 3 06 38 PM" src="https://github.com/user-attachments/assets/bb08acfa-ce26-402c-97dd-fab8251a4279">

**Comment by maniamartial** [comment]
It was depending on another private application, but fixing that.

**Comment by maniamartial** [comment]
Was solved
